### ISSUE TITLE
[Feature] 마이페이지 설정 API

### ISSUE THREAD

**Issue by miju0515** [2024-Google-Solution-Challenge-Team5/Backend#29]
## 🔨 Describe
- 마이페이지에 들어갈 계정 이름 변경, 푸시 알림 설정, 폐기 리워드 확인 API를 구현한다

## ✅ Tasks
- [ ] 계정 이름 변경
- [ ] 푸시 알림 설정
- [ ] 폐기 리워드 확인
