### ISSUE TITLE
[Feature] 구급상자 조회 & 추가하기 API

### ISSUE THREAD

**Issue by pingowl** [2024-Google-Solution-Challenge-Team5/Backend#3]
## 🔨 Describe
- 사용자는 구급상자 목록을 조회할 수 있고, 생성 또는 초대를 통해 구급상자를 추가할 수 있다.

## ✅ Tasks
- [x] 구급상자 추가 (생성) API
- [x] 구급상자 추가 (초대) API
- [x] 구급상자 목록 조회 API
