### ISSUE TITLE
[Feature] 구급상자 세부설정 API

### ISSUE THREAD

**Issue by pingowl** [2024-Google-Solution-Challenge-Team5/Backend#6]
## 🔨 Describe
- 사용자는 구급상자의 이름과 사진을 변경할 수 있다.

## ✅ Tasks
- [x] 구급상자 이름 변경하기 API
- [x] 구급상자 사진 변경하기 API
- [x] 구급상자 세부설정(이름, 사진, 구성원, 초대코드) 조회 API
