### ISSUE TITLE
[Feature] 의약품 상세정보 API

### ISSUE THREAD

**Issue by miju0515** [2024-Google-Solution-Challenge-Team5/Backend#9]
## 🔨 Describe
- 의약품의 상세 설명을 확인하고 날짜가 지난 의약품은 폐기 리스트로 옮길 수 있다.

## ✅ Tasks
- [ ] 의약품 상세설명 보기 API
- [x] 의약품 폐기 API
- [x] 의약품 사용 API
